crud/urls.py
from django.contrib import admin
from django.urls import path
from app.views import home
from app.views import form 
from app.views import create
from app.views import view
from app.views import edit
from app.views import update
from app.views import delete

urlpatterns =[
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('form/', form, name='form'),
    path('create/', create, name='create'),
    path('view/<int:pk>/', view, name='view'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('update/<int:pk>/', update, name='update'),
     path('delete/<int:pk>/', delete, name='delete')
    ]

app/models.py
from django.db import models

# Create your models here.

class Alunos(models.Model):
    nome = models.CharField(max_length=150)
    unidade = models.CharField(max_length=100)
    idade =  models.IntegerField()
    foto = models.ImageField(upload_to='alunos_fotos/', blank=True, null=True)

app/views.py
from django.shortcuts import redirect, render
from app.form import AlunosForm
from app.models import Alunos

# Create your views here.
def home(request):
    data ={}
    data['db'] = Alunos.objects.all()
    return render(request, 'index.html', data)


def form(request):
    data = { }
    data['form'] = AlunosForm()
    return render(request, 'form.html', data)

def create(request):
    form = AlunosForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('home')
    
    
def view(request, pk):
    data = {}
    data['db'] = Alunos.objects.get(pk=pk)
    return render(request, 'view.html', data)


def edit(request, pk):
    data = {}
    data['db'] = Alunos.objects.get(pk=pk)
    data['form'] = AlunosForm(instance=data['db'])
    return render(request, 'form.html', data)



def update(request, pk):
    data = {}
    data['db'] = Alunos.objects.get(pk=pk)
    form = AlunosForm(request.POST or None, instance=data['db'])
    if form.is_valid():
        form.save()
        return redirect('home')
    
    
    
def delete(request, pk):
    db = Alunos.objects.get(pk=pk)
    db.delete()
    return redirect('home')

app/templates/form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <style>
        /* Defina a cor de fundo desejada para o body */
        body {
            background-color: #79aa92; 
        }
    
        /* Defina a cor do texto desejada */
        h1 {
            color: #080808; /* Exemplo de cor cinza escuro */
        }
    </style>
</head>
<body>
    <div class="col-8 m-auto pt-2 pb-2 text-center">
        <h1>Cadastro</h1>
    </div>
      
    <div class="col-8 m-auto pt-2 pb-2 text-center" >
        <a href="/" class="btn btn-info">Voltar</a>
    </div>

    <div class="col-8 m-auto pt-4 pb-2 text-center">
        <form name="form" id="form" action="{% if db %}/update/{{db.id}}/{% else %}/create/{% endif %}" method="post">
            {% csrf_token %}
            <div class="form-group mt-3">nome: {{ form.nome }}</div>
            <div class="form-group mt-3">unidade: {{ form.unidade }}</div>
            <div class="form-group mt-3">idade: {{ form.idade }}</div>
            
            <div class="form-group mt-3">
                <label for="id_foto">Foto:</label>
                <input type="file" name="foto" id="id_foto" accept="image/*">
                <button type="button" id="btn-tirar-foto">Tirar Foto</button>
                <video id="video" width="400" height="300" style="display:none;"></video>
                <canvas id="canvas" width="400" height="300" style="display:none;"></canvas>
            </div>
        
            <input class="btn btn-success mt-3" type="submit" value="Salvar">
        </form>
    </div>

    <script>
        const video = document.getElementById('video');
        const canvas = document.getElementById('canvas');
        const btnTirarFoto = document.getElementById('btn-tirar-foto');

        btnTirarFoto.addEventListener('click', () => {
            navigator.mediaDevices.getUserMedia({ video: true })
                .then(stream => {
                    video.srcObject = stream;
                    video.play();
                })
                .catch(err => console.error('Erro ao acessar a câmera:', err));
        });

        video.addEventListener('canplay', () => {
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            setInterval(() => {
                canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);
            }, 10);
        });
    </script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>crud com python</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>
<style>


  /* Defina a cor de fundo desejada para o body */
  body {
            background-color: #79aa92; 

           
        }
  

   /* Defina a cor do texto desejada */
  h1 {
            color: #080808; /* Exemplo de cor cinza escuro */
        }

  
</style>

<body>
  
    <div class="col-8 m-auto pt-2 pb-2 text-center">
       <h1> Youfit <i class="fas fa-dumbbell" ></i> </h1>

       
       

       

    </div>

    <div class="col-8 m-auto pt-2 pb-2 text-center" >
        <a class="btn btn-success" href="/form" role="button">Adicionar</a>
    </div>

    <div class="col-8 m-auto pt-2 pb-2 text-center" >
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Matricula</th>
                <th scope="col">Nome</th>
                <th scope="col">Unidade</th>
                <th scope="col">Idade</th>
                <th scope="col">ações</th>
              </tr>
          
            </thead>
            <tbody>
              {% for dbs in db %}
              <tr>
                <th>{{dbs.id}}</th>
                <td>{{dbs.nome }}</td>
                <td>{{dbs.unidade}}</td>
                <td>{{dbs.idade}}</td>
                <td>

                <a href="/view/{{dbs.id}}/" class="btn btn-dark">visualizar</a>
                <a href="/edit/{{dbs.id}}/" class="btn btn-primary">Editar</a>
                <a href="/delete/{{dbs.id}}/" class="btn btn-danger">Deletar</a>
                </td>

              </tr>
              {% endfor %}
            </table>
    </div>

   

</body>
</html>

app/templates/view.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
></head>
<style>
  /* Defina a cor de fundo desejada para o body */
  body {
            background-color: #79aa92; 
        }
  

  /* Defina a cor do texto desejada */
  h1 {
            color: #080808; /* Exemplo de cor cinza escuro */
        }




</style> 
<body>
    <div class="col-8 m-auto pt-2 pb-2 text-center">
       <h1>Visualizar</h1>
    </div>
      
    <div class="col-8 m-auto pt-2 pb-2 text-center" >
        <a href="/" class="btn btn-info">Voltar</a>
    </div>

    <div class="col-8 m-auto pt-4 pb-2 text-center">
        <strong>nome: </strong>{{db.nome}} <br>
        <strong>unidade: </strong>{{db.unidade}} <br>
        <strong>idade: </strong>{{db.idade}} <br>
        
    </div>
    
</body>
</html>